version: '3.4'

services:
  auth-service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
      - redis
    networks:
      - authnetwork
    restart: on-failure

  project-service:
    build:
      context: ./ProjectService
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
      - redis
    networks:
      - authnetwork
    restart: on-failure

  task-service:
    build:
      context: ./TaskService
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
      - redis
    networks:
      - authnetwork
    restart: on-failure

  user-service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "5003:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
      - redis
    networks:
      - authnetwork
    restart: on-failure

  sqlserver:
    image:  mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "YourStrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - authnetwork

  redis:
    image: redis
    ports:
      - "6379:6379"

networks:
  authnetwork:
volumes:
  sqlvolume: